import { positionAfter, positionBetween, siteTag } from './position';

export interface Char {
  char: string;
  position: string;
  siteId: string;
}

// Everything that crosses the network. Both kinds are commutative and idempotent:
// applying the same set of operations in any order, any number of times, leaves
// every replica with the same document.
export type Operation =
  | { action: 'insert'; char: Char }
  | { action: 'delete'; position: string; siteId: string };

const keyOf = (position: string, siteId: string) => `${position}|${siteId}`;

export class CRDT {
  readonly siteId: string;
  private readonly tag: string;
  private document: Char[] = [];
  // Deleted keys are remembered rather than forgotten, so a delete that arrives
  // before its insert (the network may reorder) still wins when the insert lands.
  private tombstones = new Set<string>();

  constructor(siteId?: string) {
    this.siteId = siteId ?? (globalThis.crypto?.randomUUID?.() ?? Math.random().toString(36).slice(2));
    this.tag = siteTag(this.siteId);
  }

  // Total order over characters.
  //
  // Two users typing into the same gap at the same time can generate the same
  // position, and a sort is only as stable as the array it is given, which is in
  // arrival order and differs per machine. Breaking the tie on siteId gives every
  // character a key every replica agrees on.
  static compare(a: Char, b: Char): number {
    if (a.position !== b.position) return a.position < b.position ? -1 : 1;
    return a.siteId < b.siteId ? -1 : a.siteId > b.siteId ? 1 : 0;
  }

  /** Insert `char` so that it becomes visible index `index`. */
  localInsert(index: number, char: string): Operation {
    const prevChar = index > 0 ? this.document[index - 1] : undefined;
    const prev = prevChar ? prevChar.position : '';
    let next: string | null = index < this.document.length ? this.document[index].position : null;
    // Two concurrent characters can share a position (and differ by site). There
    // is no string strictly between equal strings, so place this one after both.
    if (next !== null && !(prev < next)) next = null;

    let position: string | null = null;
    // Continuing our own run: extend the previous character's position rather
    // than splitting the gap. Midpoint allocation gives two people typing into
    // the same gap positions that differ only in the site tag at the end, so
    // their letters alternated ("coffee beans" and "eggs" became "beeggasns").
    if (prevChar && prevChar.siteId === this.siteId) {
      const candidate = positionAfter(prev);
      if ((next === null || candidate < next) && !this.keyUsed(candidate)) position = candidate;
    }
    if (position === null) {
      // The site tag keeps positions generated by different sites distinct in
      // practice, so the siteId tie-break above rarely has to decide.
      position = positionBetween(prev, next) + this.tag;
      // Generation is deterministic, so deleting a character and typing into the
      // same gap would produce the deleted character's key again. Other replicas
      // hold that key as a tombstone and would drop the new character. Step past
      // any key this site has ever used; the result is still below next.
      while (this.keyUsed(position)) position = positionBetween(position, next) + this.tag;
    }
    const c: Char = { char, position, siteId: this.siteId };
    this.insertSorted(c);
    return { action: 'insert', char: c };
  }

  private keyUsed(position: string): boolean {
    return this.tombstones.has(keyOf(position, this.siteId)) || this.indexOfKey(position, this.siteId) >= 0;
  }

  /** Delete the character at visible index `index`. */
  localDelete(index: number): Operation {
    const c = this.document[index];
    const op: Operation = { action: 'delete', position: c.position, siteId: c.siteId };
    this.apply(op);
    return op;
  }

  apply(op: Operation): void {
    if (op.action === 'insert') {
      const { position, siteId } = op.char;
      if (this.tombstones.has(keyOf(position, siteId)) || this.indexOfKey(position, siteId) >= 0) return;
      this.insertSorted(op.char);
    } else {
      this.tombstones.add(keyOf(op.position, op.siteId));
      const i = this.indexOfKey(op.position, op.siteId);
      if (i >= 0) this.document.splice(i, 1);
    }
  }

  getText(): string {
    return this.document.map((c) => c.char).join('');
  }

  chars(): readonly Char[] {
    return this.document;
  }

  /** Visible index of a character by key, or -1. */
  indexOfKey(position: string, siteId: string): number {
    const i = this.lowerBound({ char: '', position, siteId });
    const c = this.document[i];
    return c && c.position === position && c.siteId === siteId ? i : -1;
  }

  private lowerBound(probe: Char): number {
    let lo = 0, hi = this.document.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (CRDT.compare(this.document[mid], probe) < 0) lo = mid + 1; else hi = mid;
    }
    return lo;
  }

  private insertSorted(c: Char): void {
    // Binary search for the slot, instead of pushing and re-sorting every character.
    this.document.splice(this.lowerBound(c), 0, c);
  }
}

/**
 * The operations that turn `before` into `after`, for a text box edit: one
 * contiguous replaced range, which covers typing, backspace, paste and cut.
 */
export function diffToOperations(crdt: CRDT, before: string, after: string): Operation[] {
  let start = 0;
  while (start < before.length && start < after.length && before[start] === after[start]) start++;
  let endBefore = before.length, endAfter = after.length;
  while (endBefore > start && endAfter > start && before[endBefore - 1] === after[endAfter - 1]) {
    endBefore--;
    endAfter--;
  }
  const ops: Operation[] = [];
  for (let i = endBefore - 1; i >= start; i--) ops.push(crdt.localDelete(i));
  for (let i = start; i < endAfter; i++) ops.push(crdt.localInsert(i, after[i]));
  return ops;
}
